# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pr:
  - master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
  - script: |
      git config user.email "kchau@microsoft.com"
      git config user.name "kchau@microsoft.com"
    displayName: git config

  - script: |
      yarn
    displayName: 'yarn'

  - script: |
      yarn checkchange
    displayName: 'check change files'

  - script: |
      yarn build
    displayName: 'build'

  - script: |
      yarn test
    displayName: 'test'
