name: PR

on:
  pull_request:
    branches: [main, v2]
  push:
    branches: [main, v2]

concurrency:
  # For PRs, use the ref (branch) in the concurrency group so that new pushes cancel any old runs.
  # For pushes to main, ideally we wouldn't set a concurrency group, but github actions doesn't
  # support conditional blocks of settings, so we use the SHA so the "group" is unique.
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v2') && github.sha || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Node.js from .nvmrc
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc

      - run: yarn --immutable

      - run: yarn checkchange

      - run: yarn format:check
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: build
        run: yarn lage build api --verbose

      - name: lint
        run: yarn lint --verbose

      - name: test
        run: yarn test --verbose

      - name: Check for modified files
        uses: microsoft/beachball/actions/check-for-modified-files@2183fc61cfda95fd77ab84b058723043d8b59939 # check-for-modified-files_v3

  # The docs have a separate installation (previously required for newer Node version, but still
  # helpful for keeping dependencies separate)
  docs:
    name: build docs

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: .nvmrc

      - name: Install docs dependencies
        working-directory: docs
        run: yarn --immutable

      - name: Build doc site
        working-directory: docs
        run: yarn build
