name: PR

on:
  pull_request:
    branches: [main, v2]
  push:
    branches: [main, v2]

concurrency:
  # For PRs, use the ref (branch) in the concurrency group so that new pushes cancel any old runs.
  # For pushes to main, ideally we wouldn't set a concurrency group, but github actions doesn't
  # support conditional blocks of settings, so we use the SHA so the "group" is unique.
  group: ${{ github.workflow }}-${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/v2') && github.sha || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install Node.js from .nvmrc
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc

      - run: yarn --immutable

      - run: yarn checkchange

      - run: yarn format:check
        if: ${{ matrix.os == 'ubuntu-latest' }}

      - name: build
        run: yarn lage build api --verbose

      - name: lint
        run: yarn lint --verbose

      - name: test
        run: yarn test --verbose

      - name: Check for modified files
        uses: microsoft/beachball-actions/check-for-modified-files@cf7d34819ad50dce8894b3ff99a2a7899aefee3d # v3

  # The docs have a separate installation (previously required for newer Node version, but still
  # helpful for keeping dependencies separate)
  docs:
    name: build docs

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc

      - name: Install docs dependencies
        working-directory: docs
        run: yarn --immutable

      - name: Build doc site
        working-directory: docs
        run: yarn build
