name: Release

# Release on demand only
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    # This environment contains secrets needed for publishing
    environment: release

    permissions:
      # required for npm trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          # Don't save creds in the git config (so it's easier to override later)
          persist-credentials: false

      # Prereleases from main are disabled until the canary/prerelease flow is fixed
      - name: Verify v2 branch
        run: |
          if [[ "${GITHUB_REF}" != "refs/heads/v2" ]]; then
            echo "Releases can only be triggered from the v2 branch."
            exit 1
          fi

      - name: Install Node.js from .nvmrc
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc

      - run: yarn --frozen-lockfile

      - run: yarn checkchange

      - run: yarn lage build test

      - name: Use Node 20 for publish
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 20

      - name: Install latest npm for publish
        run: npm i -g npm

      - name: Set git user
        run: |
          git config user.email "kchau@microsoft.com"
          git config user.name "Ken Chau"

      - name: Release
        run: |
          # Get the existing remote URL without creds, and use a trap (like try/finally)
          # to restore it after this step finishes
          trap "git remote set-url origin '$(git remote get-url origin)'" EXIT

          # Add a token to the remote URL for auth during release
          git remote set-url origin "https://$REPO_PAT@github.com/$GITHUB_REPOSITORY"

          yarn release
        env:
          REPO_PAT: ${{ secrets.REPO_PAT }}
